substitutions:
  _SERVICE_NAME: 'cart'  # Default service name if not overridden in the trigger
  _ENV_NAME: 'dev'

steps:
  # Step 1: Increment the version
  - name: 'ubuntu'
    id: IncrementVersion
    entrypoint: 'bash'
    args:
      - '-c'
      - './increment_version.sh'

  # Step 2: Read the version from the version file and export it
  - name: 'ubuntu'
    id: SetVersion
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat version.txt)
        echo "VERSION=${VERSION}" >> $BASH_ENV

  # Step 3: Build the Docker image using the updated version
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-east1-docker.pkg.dev/$PROJECT_ID/robot-shop-registry/${_SERVICE_NAME}-${_ENV_NAME}:${VERSION} ./${_SERVICE_NAME}

  # Step 4: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push us-east1-docker.pkg.dev/$PROJECT_ID/robot-shop-registry/${_SERVICE_NAME}-${_ENV_NAME}:${VERSION}

options:
  logging: CLOUD_LOGGING_ONLY  # Use this logging option to avoid the error

# Optional: Specify a timeout
timeout: '1200s'  # Adjust the timeout as needed
