steps:
  # Step 1: Read or initialize the version from version.txt
  - name: 'ubuntu'
    id: ReadVersion
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -f version.txt ]; then
          echo "v1" > version.txt  # Initialize version if file does not exist
        fi
        VERSION=$(cat version.txt)
        echo "VERSION=${VERSION}" > /workspace/version.env
        echo "Current version: $VERSION"


options:
  logging: CLOUD_LOGGING_ONLY  # Use this logging option to avoid the error

# Optional: Specify a timeout
timeout: '1200s'  # Adjust the timeout as needed
