# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: robotshop
  version: latest
  pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For enable ingress
# Other existing configurations...

ingress:
  enabled: true
  name: robot-shop-ingress  # Custom name for the Ingress
  namespace: robot-shop     # Specify the namespace for the Ingress
  #host: myapp.example.com   # Domain for your Ingress
  #ingressClassName: gce     # Specify the Ingress class
  annotations:              # Any additional annotations
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "robot-shop-dev-static-ip"

# For Google Managed SSL
gcp:
  managedSSL:
    enabled: true
    domains:
      - dev.techstackflow.in


# For the mini ones minikube, minishift set to true
nodeport: true

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
######################################

cart: {}

catalogue: {}

dispatch: {}

mongodb: {}

mysql: {}

payment:
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com

rabbitmq: {}

ratings: {}

redis:
  # Storage class to use with redis statefulset.
  storageClassName: default

shipping: {}

user: {}

web: {}