{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.ingress.namespace | default "default" }}  # Use namespace from values.yaml
  name: {{ .Values.ingress.name | default "robot-shop-ingress" }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- if .Values.gcp.managedSSL.enabled }}
    networking.gke.io/managed-certificates: managed-cert-for-ingress
    # SSL Redirect HTTP to HTTPS
    networking.gke.io/v1beta1.FrontendConfig: "my-frontend-config"
    {{- end }}
spec:
  #ingressClassName: {{ .Values.ingress.ingressClassName | default "gce" }}
  defaultBackend:
    service:
      name: web
      port:
        number: 8080
  rules: 
      #- host: {{ .Values.ingress.host | default "myapp.example.com" }}
    - http:
        paths:
          - path: /shipping
            pathType: Prefix
            backend:
              service:
                name: shipping  # Service name should match your web service
                port:
                  number: 8080  # The port exposed by your web service
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user  # Service name should match your web service
                port:
                  number: 8080
          - path: /rate
            pathType: Prefix
            backend:
              service:
                name: ratings  # Service name should match your web service
                port:
                  number: 80
          - path: /pay
            pathType: Prefix
            backend:
              service:
                name: payment  # Service name should match your web service
                port:
                  number: 8080
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: catalogue  # Service name should match your web service
                port:
                  number: 8080
          - path: /categories
            pathType: Prefix
            backend:
              service:
                name: catalogue  # Service name should match your web service
                port:
                  number: 8080        
          - path: /cart
            pathType: Prefix
            backend:
              service:
                name: cart  # Service name should match your web service
                port:
                  number: 8080
{{- end }}
