{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.ingress.namespace | default "default" }}  # Use namespace from values.yaml
  name: {{ .Values.ingress.name | default "robot-shop-ingress" }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "gce" }}
  rules:
    - host: {{ .Values.ingress.host | default "myapp.example.com" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web  # Service name should match your web service
                port:
                  number: 8080  # The port exposed by your web service
{{- end }}
